version: '3.9'

services:
    alpine:
        build: ./alpine
        working_dir: '${WORKING_DIR}'
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        volumes:
            - './../:${WORKING_DIR}'

    db:
        build: ./postgres
        environment:
            POSTGRES_USER: '${DB_USER}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_NAME}'
        volumes:
            - pg13:/var/lib/postgresql/data

    pgbouncer:
        image: pgbouncer/pgbouncer:latest
        depends_on:
            - db
        environment:
            DATABASES_HOST: db
            DATABASES_PORT: 5432
            DATABASES_USER: '${DB_USER}'
            DATABASES_PASSWORD: '${DB_PASSWORD}'
            DATABASES_DBNAME: '${DB_NAME}'
            PGBOUNCER_POOL_MODE: transaction
            PGBOUNCER_MAX_CLIENT_CONN: 1000

    php-cli:
        build: ./php8-cli
        working_dir: '${WORKING_DIR}'
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        depends_on:
            - pgbouncer
        environment:
            DATABASE_URL: 'pgsql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:6432/${DB_NAME}?serverVersion=13.2&charset=utf8'
        volumes:
            - './../:${WORKING_DIR}'
            - ./../var/log/php_errors.log:/var/log/php_errors.log
            - /root/.composer/cache:/root/.composer/cache
#            - ./php-cli/global.ini:/usr/local/etc/php/conf.d/global.ini
#            - ./php-cli/apcu.ini:/usr/local/etc/php/conf.d/apcu.ini
#            - ./php-cli/symfony-console-autocomplete:/etc/bash_completion.d/symfony-console-autocomplete
#            - ./php-cli/.bashrc:/root/.bashrc

    php-fpm:
        build: ./php8-fpm
        working_dir: '${WORKING_DIR}'
        depends_on:
            - pgbouncer
        environment:
            DATABASE_URL: 'pgsql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:6432/${DB_NAME}?serverVersion=13.2&charset=utf8'
        volumes:
            - './../:${WORKING_DIR}'
            - ./../var/log/php-fpm_errors.log:/var/log/php-fpm_errors.log
#            - ./php-fpm/global.ini:/usr/local/etc/php/conf.d/global.ini
#            - ./php-fpm/apcu.ini:/usr/local/etc/php/conf.d/apcu.ini

volumes:
    pg13:
